# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace: codefresh  # Need to change 3 place. All ingress namespaces.

coreapi:
  name: core-api 
  namespace: codefresh # Please mention all the namespaces
  containername: core-api
  replicaCount: 1
  repository: gcr.io/pharmacy-265821/core-api:68aa917f7bf1c73c88a44f07ffa19ff652648680 
  pullPolicy: Always
  service:
    type: NodePort
    port: 80
    targetport: 3000
  ingress:
    enabled: true
    secrets:
    - name: core-api-sb-tls
      namespace: codefresh
    annotations: {}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.falsepill.com
      - host: dev-sandbox-healthchat.falsepill.com
    paths: 
      - / 
    tls: 
    - secretName: core-api-sb-tls
      hosts:
        - api.falsepill.com
        - dev-sandbox-healthchat.falsepill.com    


dashboard:
  name: dashboard-api
  namespace: codefresh # Please mention all the namespaces
  containername: dashboard-api
  repository: gcr.io/pharmacy-265821/dashboard-api:bd8e1ff0c0dcc2d89624e7cb5a70cbc56d623ef1
  pullPolicy: Always
  replicaCount: 1
  service:
    type: NodePort
    port: 80
    targetport: 3000
  ingress:
    enabled: true
    secrets:
    - name: dashboard-api-sb-tls
      namespace: codefresh
    annotations: {}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    hosts:
      - host: dashboard-api.falsepill.com
    paths: 
      - / 
    tls: 
    - secretName: dashboard-api-sb-tls
      hosts:
        - dashboard-api.falsepill.com
        

postit:
  name: postit
  namespace: codefresh
  containername: postit-tpapp
  repository: gcr.io/pharmacy-265821/postit:573839a0c1a80e4afba31e3fe55a806b91755683 
  pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP

sqs:
  name: sqs
  namespace: codefresh
  containername: sqs-tpapp
  repository: roribio16/alpine-sqs:latest 
  pullPolicy: Always
  replicaCount: 1
  service:
    type: NodePort
    httpstandard:
      port: 80
      targetport: 9324
    http:
      port: 9324
      targetport: 9324
    admin:
      port: 9325
      targetport: 9325

truefill:
  name: truefill
  namespace: codefresh
  containername: truefill
  repository: gcr.io/pharmacy-265821/truefill:0672692515617bd8f4f401e93acf6e7d05991c98
  pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
      
mongo:
  name: mongo
  namespace: codefresh
  containername: mongo-app
  repository: mongo:4.2.0 
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 27017
    targetport: 27017

#aws:
#  AWS_ACCESS_KEY_ID: QUtJQTU2STZZSUVPVzVLSzdHUEk=
#  AWS_DEFAULT_REGION: dXMtZWFzdC0x
#  AWS_SECRET_ACCESS_KEY: YmY3VFRJY0VEc2ozT1NoR2VZWHBOZGdjdHVMNW0rYy9YdEloQmtNYw==

vault:
  JWT_TOKEN: ZWI2ZjQxMzM5ZjA0MzU5OGYzMjNiZjQ4Y2FhNzdmMjJjYmRiNGVhOTU4MzYwZDE0OTY3NmViODNiMTBiM2Y5NGVlZGYzMTNiMzIwYmI2NmFlOTQwODUzYWVkODcxMzdmOTVmNmVlOTgyYTRhMTk4MDg0ZTJhOTM1ZjIwNDI2YTc=
  MYSQL_PASSWORD: dHJ1ZXBpbGw=
  NPM_TOKEN: Y2RlZDBmZTg1ZDdkZDVmODhkZDU2ZjgxNTBkNmNiZWIyODBhZGU4Yw==
  ROLLBAR_TOKEN: YzdiYThhZTA2M2FhNDNlNDhlY2FhMDQwMmFiYTYxZjA=

configmap:
  ARGUS_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/argus_dev-sandbox
  BOM_ASSIGNMENT_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/order_bom_assignment_dev-sandbox
  ELASTIC_APM_LOG_UNCAUGHT_EXCEPTIONS: "true"
  ELASTIC_APM_SERVER_URL: http://apm-server.default:8200
  EVENT_LOGGER_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/event_logger_dev-sandbox
  FILL_REQUESTS_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/fill_requests_dev-sandbox
  LOCATION_ASSIGNMENT_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/location_assignment_dev-sandbox
  MONGO_CONNECTION: mongodb://mongo:27017/admin
  MONGO_DB: admin
  MYSQL_HOST: 34.201.31.226
  MYSQL_PORT: "3307"
  MYSQL_USER: root
  NURXRECOVERY_QUEUE: http://sqs/queue/nurx_recovery
  PIONEER_EVENTS_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/pioneer_events_sandbox
  POSTIT_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/postit_callbacks_dev-sandbox
  PYONEER_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/pyoneer_dev-sandbox
  QUEUE_NURXRECOVERY: http://sqs/queue/nurx_recovery
  QUEUE_POSTIT: https://sqs.us-east-1.amazonaws.com/958379082013/postit_callbacks_dev-sandbox
  READY_TO_FILL_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/TCGRX_ready_to_fill_dev-sandbox
  SIMIT_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/simit
  SQS_ENDPOINT: https://sqs.us-east-1.amazonaws.com/958379082013/
  TCGRX_REQUEST_QUEUE: https://sqs.us-east-1.amazonaws.com/958379082013/TCGRX_requests_dev-sandbox
  TCGRX_S3_BUCKET_URL: tcgrx-orders-dev-sandbox



imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



ingress:
  enabled: true
  annotations: {}
  kubernetes.io/ingress.class: nginx
  cert-manager.io/cluster-issuer: letsencrypt-prod
  certmanager.k8s.io/acme-http01-edit-in-place: "true"
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: api.falsepill.com
    - host: dev-sandbox-healthchat.falsepill.com
  paths: 
    - / 
  tls: 
  - secretName: core-api-sb-tls
    hosts:
      - api.falsepill.com
      - dev-sandbox-healthchat.falsepill.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

configurationFiles: 
  elasticmq.conf.file: |-
    include classpath("application.conf")

    queues {
        simit {
            defaultVisibilityTimeout = 15 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
        fill_requests {
            defaultVisibilityTimeout = 15 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
        postit_callbacks {
            defaultVisibilityTimeout = 15 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
        pyoneer-api {
            defaultVisibilityTimeout = 15 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
        pharmacy_automation {
            defaultVisibilityTimeout = 15 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
    }

    rest-sqs {
        enabled = true
        bind-port = 9324
        bind-hostname = "0.0.0.0"
        // Possible values: relaxed, strict
        sqs-limits = strict
    }
