apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "mongo.Labels" . | nindent 4 }}
  name: data-mongo-0
  namespace: {{ .Values.mongo.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi